// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_level_3 = "CgkI4fGcnusBEAIQAg"; // <GPGSID>
        public const string leaderboard_level_2 = "CgkI4fGcnusBEAIQAQ"; // <GPGSID>
        public const string leaderboard_level_1 = "CgkI4fGcnusBEAIQAA"; // <GPGSID>
        public const string achievement_its_only_beginning = "CgkI4fGcnusBEAIQDQ"; // <GPGSID>
        public const string leaderboard_level_7 = "CgkI4fGcnusBEAIQBg"; // <GPGSID>
        public const string leaderboard_level_6 = "CgkI4fGcnusBEAIQBQ"; // <GPGSID>
        public const string leaderboard_level_5 = "CgkI4fGcnusBEAIQBA"; // <GPGSID>
        public const string leaderboard_level_4 = "CgkI4fGcnusBEAIQAw"; // <GPGSID>
        public const string achievement_easter_egg = "CgkI4fGcnusBEAIQDg"; // <GPGSID>
        public const string achievement_keep_calm_and_play_next_levels = "CgkI4fGcnusBEAIQDA"; // <GPGSID>
        public const string leaderboard_level_8 = "CgkI4fGcnusBEAIQBw"; // <GPGSID>
        public const string leaderboard_level_10 = "CgkI4fGcnusBEAIQCQ"; // <GPGSID>
        public const string leaderboard_level_9 = "CgkI4fGcnusBEAIQCA"; // <GPGSID>
        public const string achievement_youre_amazing = "CgkI4fGcnusBEAIQCw"; // <GPGSID>
        public const string achievement_ole_this_is_hole = "CgkI4fGcnusBEAIQCg"; // <GPGSID>

}

