// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_level_3 = "CgkIkOen0OUSEAIQCA"; // <GPGSID>
        public const string leaderboard_level_2 = "CgkIkOen0OUSEAIQBw"; // <GPGSID>
        public const string leaderboard_level_1 = "CgkIkOen0OUSEAIQBg"; // <GPGSID>
        public const string leaderboard_level_7 = "CgkIkOen0OUSEAIQDA"; // <GPGSID>
        public const string leaderboard_level_6 = "CgkIkOen0OUSEAIQCw"; // <GPGSID>
        public const string leaderboard_level_5 = "CgkIkOen0OUSEAIQCg"; // <GPGSID>
        public const string leaderboard_level_4 = "CgkIkOen0OUSEAIQCQ"; // <GPGSID>
        public const string achievement_easter_egg = "CgkIkOen0OUSEAIQAQ"; // <GPGSID>
        public const string achievement_keep_calm_and_play_next_levels = "CgkIkOen0OUSEAIQBA"; // <GPGSID>
        public const string leaderboard_level_8 = "CgkIkOen0OUSEAIQDQ"; // <GPGSID>
        public const string achievement_its_only_beginning = "CgkIkOen0OUSEAIQAw"; // <GPGSID>
        public const string leaderboard_level_10 = "CgkIkOen0OUSEAIQDw"; // <GPGSID>
        public const string leaderboard_level_9 = "CgkIkOen0OUSEAIQDg"; // <GPGSID>
        public const string achievement_youre_amazing = "CgkIkOen0OUSEAIQBQ"; // <GPGSID>
        public const string achievement_ole_this_is_hole = "CgkIkOen0OUSEAIQAg"; // <GPGSID>

}

